name: Build and push semantic image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-semantic:
    name: Build and push semantic-only image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push semantic-only Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.semantic
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-semantic:latest