name: Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file for runtime (from secret)
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > ./.env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-public:latest
          # Note: do NOT bake secrets into the image. We add .env to repo root for runtime only.

      # OPTIONAL: you can add deployment steps here (e.g., kubectl, ssh deploy, or platform-specific deploy)

      - name: Cleanup .env
        run: |
          shred -u ./.env || rm -f ./.env || true
