name: Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-public:latest

  deploy-to-host:
    name: Deploy to host (inject secrets at deploy time)
    runs-on: ubuntu-latest
    needs: [build-and-deploy, build-and-push-semantic]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to remote host via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || '22' }}
          script: |
            set -e
            DEPLOY_DIR="/home/${{ secrets.DEPLOY_USER }}/tb_app"
            mkdir -p "$DEPLOY_DIR"
            # Write .env with the GEMMA API key on the remote host (only on host filesystem)
            cat > "$DEPLOY_DIR/.env" <<'EOF'
            GEMMA_API_KEY=${{ secrets.GEMMA_API_KEY }}
            EOF
            # Pull the just-built image and restart container
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-public:latest
            docker rm -f tb || true
            docker run -d --env-file "$DEPLOY_DIR/.env" --name tb -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-public:latest

  build-and-push-semantic:
    name: Build and push semantic-only image
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push semantic-only Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.semantic
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tb-chatbot-semantic:latest